d-Rickyy-b/pastepwn

analyzers/__init__.py, analyzers/alwaystrueanalyzer.py, analyzers/creditcardanalyzer.py, analyzers/genericanalyzer.py, analyzers/mailanalyzer.py, analyzers/pastebinurlanalyzer.py, analyzers/regexanalyzer.py, analyzers/urlanalyzer.py, analyzers/wordanalyzer.py
Also added an optional `resolve` constructor arg, which if set to True will attempt to validate the URL it matches by resolving it with urllib.
This PR addresses issue #14
=> Adding a URLAnalyzer and PastebinURLAnalyzer to address issue #14

analyzers/__init__.py, analyzers/bcrypthashanalyzer.py, analyzers/md5hashanalyzer.py, analyzers/shahashanalyzer.py
This PR addresses issue #15.
This PR should be merged before my other MR for minimal merge conflict resolution.
=> Adding HashAnalyzers for MD5, SHA, and bcrypt hashes.

analyzers/wordanalyzer.py
=> FEATURE: Blacklist for WordAnalyzer

database/__init__.py, database/mysqldb.py, database/sqlitedb.py
The mysql connector package was not added to the requirements yet.
=> FEATURE: Implement mysql and sqlite

analyzers/__init__.py, analyzers/ibananalyzer.py, analyzers/tests/test_ibananalyzer.py
As requested in issue #35
Not sure if this needs to be attached somehow, or it's automatically loaded?
=> Add IBAN analyzer

analyzers/ibananalyzer.py
Were forgotten in the last PR for #35
=> add description and name to IBAN analyzer

actions/databaseaction.py, actions/genericaction.py, actions/logaction.py, actions/savefileaction.py, actions/savejsonaction.py, actions/telegramaction.py, actions/webhookaction.py
=> Dot local imports for all actions

core/pastepwn.py, requirements.txt, util/request.py
A singleton is needed to setup the request class with proxy settings etc.
=> Rework of the request util class

pastepwn/core/pastepwn.py, pastepwn/database/sqlitedb.py
sqlite did not work as I intended it. Now it should be fine.
=> Fix sqlite issues

.travis.yml, setup.py
Use travis tag to build the pypi package
=> Pypi setup changes

.gitignore, README.md, pastepwn/analyzers/basicanalyzer.py, pastepwn/analyzers/wordanalyzer.py, pastepwn/scraping/pastebin/exceptions/__init__.py, pastepwn/scraping/pastebin/exceptions/emptybodyexception.py, pastepwn/scraping/pastebin/exceptions/pastedeletedexception.py, pastepwn/scraping/pastebin/exceptions/pasteemptyexception.py, pastepwn/scraping/pastebin/exceptions/pastenotreadyexception.py, pastepwn/scraping/pastebin/pastebinscraper.py
If a downloaded paste has no content yet or was already deleted, then these checks make sure that it will be donwloaded properly or skipped.
=>  FEATURE: Implement check for downloaded pastes

pastepwn/analyzers/__init__.py, pastepwn/analyzers/phonenumberanalyzer.py
Does this work? Let me know if I did something improperly. I am trying to learn!
Thanks!
=> Phone number analyzer #90

pastepwn/analyzers/shahashanalyzer.py, pastepwn/analyzers/tests/shahashanalyzer_test.py
Addresses #101.
SHAHashAnalyzer now matches SHA- 1, 224, 256, 384, and 512 hashes. Also added a unit test.
Let me know if there're any necessary changes! 😄
=> Add unit test for SHAHashAnalyzer

pastepwn/analyzers/__init__.py, pastepwn/analyzers/steamkeyanalyzer.py, pastepwn/analyzers/tests/steamkeyanalyzer_test.py
Addresses #96 (recognizing steam keys via the Regex Analyzer)
=> Added steam key analyzer

examples/example.py, pastepwn/core/pastepwn.py
- To fix #92 .
- Imported PastebinScraper.
- Initialized and added the scraper if there are no scrapers in the scraping handler.
=> Add PastebinScraper by default

pastepwn/analyzers/__init__.py, pastepwn/analyzers/originkeyanalyzer.py, pastepwn/analyzers/tests/originkeyanalyzer_test.py
I checked this regex against a pastebin with origin and steam keys in it.  It matches on Origin keys.
=> Added Origin key analyzer

pastepwn/actions/__init__.py, pastepwn/actions/discordaction.py
=> add Discord Action

pastepwn/analyzers/__init__.py, pastepwn/analyzers/adobekeyanalyzer.py, pastepwn/analyzers/md5hashanalyzer.py, pastepwn/analyzers/tests/adobekeyanalyzer_test.py, pastepwn/analyzers/tests/md5hashanalyzer_test.py
=> Add Adobe Key Analyzer

pastepwn/analyzers/epickeyanalyzer.py, pastepwn/analyzers/tests/epickeyanalyzer_test.py
- improved regex to better match the boundaries of the key to not include more segments than needed
- added a test for too many segments
=> Updated Epic Key Analyzer

pastepwn/analyzers/__init__.py, pastepwn/analyzers/base64analyzer.py, pastepwn/analyzers/tests/base64analyzer_test.py
Implementation of a base64 analyser.
- Created a simple class which extends RegexAnalyzer class.
- Added unit tests with some edge cases.
- Fixed regex to only match base64 encoded strings and not empty strings.
[https://github.com/d-Rickyy-b/pastepwn/issues/120](https://github.com/d-Rickyy-b/pastepwn/issues/120)
=> Base64 Analyser

pastepwn/analyzers/adobekeyanalyzer.py, pastepwn/analyzers/battlenetkeyanalyzer.py, pastepwn/analyzers/md5hashanalyzer.py, pastepwn/analyzers/microsoftkeyanalyzer.py, pastepwn/analyzers/originkeyanalyzer.py, pastepwn/analyzers/shahashanalyzer.py, pastepwn/analyzers/steamkeyanalyzer.py, pastepwn/analyzers/uplaykeyanalyzer.py
changed the regex for the key analyzers to better match boundary situations
=> Updated Key Analyzers

pastepwn/analyzers/__init__.py, pastepwn/analyzers/slackwebhookanalyzer.py, pastepwn/analyzers/tests/slackwebhookanalyzer_test.py
Slack Webhook URL regex and unit test added
=> Implement Slack Webhook Analyzer

pastepwn/analyzers/__init__.py, pastepwn/analyzers/awsaccesskeyanalyzer.py, pastepwn/analyzers/tests/awsaccesskeyanalyzer_test.py
AWS Access Key ID Regex and unittest
=> Add AWS Access Key ID Analyzer

pastepwn/database/mongodb.py, pastepwn/database/sqlitedb.py, pastepwn/database/tests/mongodb_test.py, pastepwn/database/tests/sqlite_test.py
#48 
I implemented the MongoDB test and update first. Will do MySQL and SQLite later!
=> Database insert tests

pastepwn/core/tests/paste_test.py
Extends tests so they now fail with the bug in my earlier PR. 
Add test of string representation of Paste object.
=> ADD: Extend and add unittests

pastepwn/analyzers/tests/creditcardanalyzer_test.py
=> CC Analyze unit test

pastepwn/analyzers/__init__.py, pastepwn/analyzers/base64analyzer.py, pastepwn/analyzers/base64asciianalyzer.py, pastepwn/analyzers/tests/base64analyzer_test.py, pastepwn/analyzers/tests/base64asciianalyzer_test.py
Add new base64asciianalyzer, create test suite for base64asciianalyzer (with all parent tests included), and add more new to base64analyzer.
=> feat(analyzers): Implement base64asciianalyzer

CHANGELOG.md, pastepwn/analyzers/basicanalyzer.py, pastepwn/analyzers/tests/basicanalyzer_test.py
This targets issue #180
I have added tests and implemented an optional unique_matches param in the BasicAnalyzer.match() method.
I have also updated the changelog.
=> Implemented a unique function for matches

CONTRIBUTING.md
Created CONTRIBUTING.md containing Contributing Guidelines for Pastepwn. It ended up more extensive than I originally imagined, so let me know your thoughts!
=> docs: added contributing guidelines documentation with CONTRIBUTING.md
